### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by wzc520pyfm** [wzc520pyfm/ant-design-x-vue#1]
Ant-design-x-vue Roadmap

主要
- [ ] 支持React版所有组件（🔥）
    - [x] XProvider
    - [x] Bubble & BubbleList
    - [ ] Conversations
    - [ ] Welcome
    - [ ] Prompts
    - [ ] Attachment
    - [ ] Sender
    - [ ] Suggestion
    - [ ] ThoughtChain
    - [ ] useXAgent
    - [ ] useXChat
    - [ ] XStream
    - [ ] XRequest
- [ ] 持续同步上油React版功能更新/问题修复
- [ ] 文档底部支持展示贡献者
- [ ] 同步React版文档内容（比如“设计”模块）
- [ ] 文档demo支持Stackblitz预览
- [ ] 文档demo代码添加一般setup示例
- [ ] 文档国际化
- [ ] 文档支持暗黑模式（hold on）

已知问题
- [ ] 样式响应式中断，动态切换亮暗模式时样式不更新

周边/规划

- [ ] 更强大的CI/CD、github Action
- [ ] 同步React版官网
- [ ] 测试覆盖率
- [ ] 完善类型系统
- [ ] monrepo
- [ ] 构建优化

**Comment by linhf123** [comment]
我来认领 Sender 和 ThoughtChain

**Comment by wzc520pyfm** [comment]
> 我来认领 Sender 和 ThoughtChain

Thanks~! You do!

**Comment by zhuba-Ahhh** [comment]
@wzc520pyfm的是都可以认领的是吧

**Comment by wzc520pyfm** [comment]
> @wzc520pyfm的是都可以认领的是吧

那些是我在开发中的，不过你也可以继续查缺补漏，或者挑选其他任务❤️

**Comment by yuguaa** [comment]
monrepo->monorepo

**Comment by zoeyzhao19** [comment]
Is anyone working on the `monorepo`? 👀

**Comment by EralChen** [comment]
#152  ThoughtChain 展开/收起动画

**Comment by wzc520pyfm** [comment]
> 认领一下attachments动画

Thanks~! You do!❤️

**Comment by Rich-wl** [comment]
支持vue2 =>是当前的组件直接兼容 还是其它方案

**Comment by wzc520pyfm** [comment]
> 支持vue2 =>是当前的组件直接兼容 还是其它方案

monorepo完成后以单独的npm包提供

**Comment by Rich-wl** [comment]
> > 支持vue2 =>是当前的组件直接兼容 还是其它方案
> 
> monorepo([#342](https://github.com/wzc520pyfm/ant-design-x-vue/pull/342))完成后以单独的npm包提供

不提供源码吗

**Comment by wzc520pyfm** [comment]
> > > 支持vue2 =>是当前的组件直接兼容 还是其它方案
> > 
> > 
> > monorepo([#342](https://github.com/wzc520pyfm/ant-design-x-vue/pull/342))完成后以单独的npm包提供
> 
> 不提供源码吗

提供，仍然在这个仓库里开发

**Comment by linhf123** [comment]
认领一下  【在线playground】

**Comment by webvs2** [comment]
playground
